spring:
  data:
    mongodb:
      host: localhost
      username: 2F4st2FurY
      password: ActAF00l
      port: 27017
      database: Start

server:
  context-path: /start
  port: 8090  
    
swagger:
  groupName: Start
  pathRegex: /v1/*.*
  title: Start API
  version: 1.0.0

app:
  name: start
  
jwt:
  header: Authorization
  expires_in: 30000 # 5 minutes
  mobile_expires_in: 60000 # 10 minutes
  secret: josesilva
  